<?php

namespace Acme\InfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactusRepository extends EntityRepository
{
}
