<?php

namespace Acme\InfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FrontRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrontRepository extends EntityRepository
{
}
