<?php

namespace Acme\InfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestimonialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonialsRepository extends EntityRepository
{
    public function getIdCount() {
    //Create query builder for languages table
    $qb = $this->createQueryBuilder('l');
    //Add Count expression to query
    $qb->add('select', $qb->expr()->count('l'));
    //Get our query
    $q = $qb->getQuery();
    //Return number of items
    return $q->getSingleScalarResult();
    }
}
