<?php

namespace Acme\FooterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FollowusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowusRepository extends EntityRepository
{
}
